Repository RevenueCat/purchases-kmp, pull requests merged in 2024-09, with the labels that each got.

#171 Adds v1 migration guide
  migrations/1.0.0-MIGRATION.md
  migrations/1.0.0-beta.3-MIGRATION.md
Labels: docs

#172 Greatly simplifies how Price.amountMicros is determined on iOS.
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  iosApp/Podfile.lock
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Price.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/PromotionalOffer.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProductDiscount.ios.kt
Labels: refactor

#175 The :update_hybrid_common lane also updates Podfile.lock.
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#176 Fixes an incorrect cast to Package.
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offering.ios.kt
Labels: fix

#179 Fixes a typo in the Fastfile.
  fastlane/Fastfile
Labels: ci

#183 Update Gemfile to fix dependabot
  Gemfile
Labels: ci

#184 Update fastlane plugin version
  Gemfile.lock
Labels: ci

#186 Update RELEASING.md
  RELEASING.md
Labels: pr:docs

#196 Passes the right contexts to the automatic-bump job.
  .circleci/config.yml
Labels: pr:ci

#197 Make sure the version gets automatically updated in the podspec files too
  core/core.podspec
  fastlane/Fastfile
  mappings/mappings.podspec
  models/models.podspec
  revenuecatui/revenuecatui.podspec
Labels: pr:ci

#187 Makes issue identifiers clickable in Android Studio
  .gitignore
  .idea/vcs.xml
Labels: pr:build

#188 Moves most enums to the models package
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementVerificationModeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/ProductTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreKitVersionAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreProductAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/VerificationResultAPI.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/MovedModels.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesConfiguration.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosTest/kotlin/com/revenuecat/purchases/kmp/PurchasesConfigurationTests.kt
  either/api/either.api
  either/api/either.klib.api
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/CacheFetchPolicy.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/ProductCategory.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/ProductType.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasingData.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/VerificationResult.android.kt
  mappings/src/commonTest/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasesAreCompletedByTests.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/CacheFetchPolicy.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/ProductType.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasingData.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreKitVersion.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/VerificationResult.ios.kt
  mappings/src/iosTest/kotlin/com/revenuecat/purchases/kmp/mappings/StoreKitVersionTests.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfos.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/CacheFetchPolicy.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/EntitlementVerificationMode.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/ProductType.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasingData.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreKitVersion.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/VerificationResult.kt
  result/api/result.api
  result/api/result.klib.api
  result/src/commonMain/kotlin/com/revenuecat/purchases/kmp/result/Result.kt
Labels: pr:refactor

#189 Moves CustomerInfo to the models package
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CustomerInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfosAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PaywallListenerAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/CustomerInfoSection.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/EntitlementInfoRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/rememberLoggingPaywallListener.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/MovedModels.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesConfiguration.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  datetime/api/datetime.api
  datetime/api/datetime.klib.api
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/CustomerInfo.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/EntitlementInfo.kt
  either/api/either.klib.api
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/CustomerInfo.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfos.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Store.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/CustomerInfo.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfos.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.android.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/CustomerInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/EntitlementInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/EntitlementInfos.kt
  result/api/result.klib.api
  result/src/commonMain/kotlin/com/revenuecat/purchases/kmp/result/Result.kt
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallListener.kt
Labels: pr:refactor

#190 Moves Offerings to the models package
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferingAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferingsAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PackageAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PackageTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PaywallListenerAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PaywallOptionsAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PresentedOfferingContextAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreProductAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/SubscriptionOptionAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/Screen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/OfferingsSection.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/PackageRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/PresentedOfferingContextRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/PresentedOfferingTargetingContextRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/rememberLoggingPaywallListener.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/MovedModels.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  either/api/either.api
  either/api/either.klib.api
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offering.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Package.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/PresentedOfferingContext.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/SubscriptionOption.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offering.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Package.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/PresentedOfferingContext.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/StoreProduct.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Offering.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Offerings.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Package.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PresentedOfferingContext.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.kt
  result/api/result.api
  result/api/result.klib.api
  result/src/commonMain/kotlin/com/revenuecat/purchases/kmp/result/Result.kt
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallListener.kt
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptions.kt
Labels: pr:refactor

#191 Moves errors to the models package
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PaywallListenerAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesExceptionAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesTransactionExceptionAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/rememberLoggingPaywallListener.kt
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/MovedModels.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  either/api/either.api
  either/api/either.klib.api
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/errors.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/errors.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.android.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasesException.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasesTransactionException.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/errors.kt
  result/src/commonMain/kotlin/com/revenuecat/purchases/kmp/result/Result.kt
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallListener.kt
Labels: pr:refactor

#192 Moves miscellaneous types to the models package
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/ReplacementModeAPI.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/MovedModels.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesConfiguration.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosTest/kotlin/com/revenuecat/purchases/kmp/PurchasesConfigurationTests.kt
  mappings/src/commonMain/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasesAreCompletedBy.kt
  mappings/src/commonTest/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasesAreCompletedByTests.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DangerousSettings.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/GoogleReplacementMode.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasesAreCompletedBy.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/ReplacementMode.kt
Labels: pr:refactor

#193 Moves LogHandler and LogLevel to the :core module
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/LogHandler.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/LogHandler.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/LogHandler.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  models/api/models.api
  models/api/models.klib.api
Labels: pr:refactor

#194 Moves PurchasesDelegate to the :core module
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/PurchasesDelegate.android.kt
  models/api/models.api
  models/api/models.klib.api
Labels: pr:refactor

#195 Enables uniquePackageNames and sets the namespace for the :models module
  gradle.properties
  models/build.gradle.kts
Labels: pr:refactor

#205 Runs the update-purchases-hybrid-common-version job on macOS.
  .circleci/config.yml
Labels: pr:ci, pr:other

#208 Bump fastlane-plugin-revenuecat_internal from 5140dbc to 55a0455
  Gemfile.lock
Labels: pr:other

#214 Fixes the PurchasesDelegate being deallocated on iOS
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
Labels: pr:fix

#207 Migrate GitHub Actions to CircleCI
  .circleci/config.yml
  .github/workflows/main.yml
  .github/workflows/on_release_tag.yml
  .github/workflows/pull_request.yml
Labels: pr:other

#209 Parallelizes CI jobs by platform
  .circleci/config.yml
Labels: pr:other

#210 Saves and restores the Kotlin/Native compiler on CI
  .circleci/config.yml
Labels: pr:other

#215 Enables incremental builds per workflow.
  .circleci/config.yml
Labels: pr:other

#220 Fixes requirements of the hold job.
  .circleci/config.yml
Labels: pr:other

#221 Updates Fastlane plugin to 5b2e35c6985e02b5911c53ebe4d071e742e03ccc
  Gemfile.lock
Labels: pr:other

#226 Skips publishing SNAPSHOT if the current version is not a SNAPSHOT.
  fastlane/Fastfile
Labels: pr:other
