Repository RevenueCat/purchases-kmp, pull requests merged in 2024-10, with the labels that each got.

#234 Attempts to fix ffi by removing the platform specification.
  Gemfile.lock
Labels: pr:other

#238 Fixes a typo in the Fastfile
  fastlane/Fastfile
Labels: pr:other

#243 Adds `Offerings.getCurrentOfferingForPlacement()`
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferingsAPI.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Offerings.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Offerings.kt
Labels: pr:feat

#246 Updates Compose Multiplatform to 1.7.0.
  gradle/libs.versions.toml
  iosApp/Podfile.lock
Labels: pr:fix

#247 Fixes iOS PaywallFooter height
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallFooter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
Labels: pr:fix

#253 Support displaying deferred win-back StoreKit messages
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreMessageTypeAPI.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreMessageType.kt
Labels: pr:feat, feat:Win-Back Offers
