Repository RevenueCat/purchases-kmp, pull requests merged in 2024-08, with the labels that each got.

#137 Remove expect/actual from enums that lack extra properties
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountPaymentModeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/LogLevelAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  core/api/core.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.ios.kt
  either/api/either.api
  result/api/result.api
Labels: refactor

#141 Temporarily reverts "Remove expect/actual from enums without extra properties (#137)"
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountPaymentModeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/LogLevelAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  core/api/core.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.ios.kt
  either/api/either.api
  result/api/result.api
Labels: refactor

#142 Adds required Kotlin test dependencies to :core
  core/build.gradle.kts
  gradle/libs.versions.toml
Labels: test

#136 Appends PHC version to the library version as build metadata
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#143 Reenables #137
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountPaymentModeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/LogLevelAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/CacheFetchPolicyAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/OwnershipTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodTypeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreAPI.kt
  core/api/core.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/CacheFetchPolicy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/LogLevel.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountPaymentMode.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.ios.kt
  either/api/either.api
  result/api/result.api
Labels: refactor

#145 [DO NOT MERGE] More StoreTransaction iOS constructors
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreTransaction.ios.kt
  core/src/iosTest/kotlin/com/revenuecat/purchases/models/StoreTransactionTests.ios.kt
Labels: refactor

#146 Adds the git-town config to source control.
  .git-branches.toml
Labels: build

#149 Auto-formats Purchases.ios.kt.
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
Labels: refactor

#148 Introduces PrintLnLogHandler to fix a test.
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PrintLnLogHandler.kt
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PurchasesConfigurationTests.kt
Labels: test

#150 Add InstallmentInfos
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/InstallmentsInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/SubscriptionOptionAPI.kt
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.ios.kt
Labels: feat

#139 Adopt Latest PHC Version
  .github/workflows/main.yml
  .github/workflows/pull_request.yml
  README.md
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/InstallmentsInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreKitVersionAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/SubscriptionOptionAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesAreCompletedByAPI.kt
  core/api/core.api
  core/api/core.klib.api
  core/build.gradle.kts
  core/core.podspec
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesConfiguration.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/StoreKitVersion.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.kt
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PrintLnLogHandler.kt
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedByTests.kt
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/PurchasesConfigurationTests.kt
  core/src/commonTest/kotlin/com/revenuecat/purchases/kmp/StoreKitVersionTests.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/InstallmentsInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreTransaction.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.ios.kt
  core/src/iosTest/kotlin/com/revenuecat/purchases/models/StoreTransactionTests.ios.kt
  gradle/libs.versions.toml
  iosApp/Podfile
  iosApp/Podfile.lock
  migrations/1.0.0-beta.3-MIGRATION.md
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/build.gradle.kts
  revenuecatui/revenuecatui.podspec
Labels: dependencies, breaking, feat

#152 Release/1.0.0-beta.3
  CHANGELOG-LATEST.md
  CHANGELOG.md
  VERSIONS.md
  gradle/libs.versions.toml
  migrations/1.0.0-beta.3-MIGRATION.md
Labels: next_release

#155 Calls out WorkManager specifically in the initialization error message.
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/di/AndroidProvider.kt
Labels: refactor

#147 Refactor StoreProduct and its dependencies
  Gemfile.lock
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferPaymentModeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PackageAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodUnitAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PresentedOfferingContextAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PricingPhaseAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/ProductTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/StoreProductAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/OfferPaymentModeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PeriodUnitAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/ProductTypeAPI.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Package.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PresentedOfferingContext.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/ProductType.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/OfferPaymentMode.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/Period.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/Price.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/PricingPhase.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/PromotionalOffer.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasingData.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProductDiscount.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOptions.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PresentedOfferingContext.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ProductType.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/OfferPaymentMode.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Period.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Price.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PricingPhase.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PromotionalOffer.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasingData.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProductDiscount.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOptions.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Package.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PresentedOfferingContext.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ProductType.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/OfferPaymentMode.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/Period.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/Price.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/PricingPhase.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/PromotionalOffer.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/PurchasingData.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProductDiscount.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOptions.ios.kt
  either/api/either.api
  either/api/either.klib.api
  result/api/result.api
  result/api/result.klib.api
Labels: refactor

#158 Fixes after rebase
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/SubscriptionOption.android.kt
Labels: refactor

#159 Move `CustomerInfo` to non-expect classes and use new mappings and models modules
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CustomerInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfosAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/TransactionAPI.kt
  build.gradle.kts
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/CustomerInfo.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfos.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.android.kt
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/models/Transaction.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/CustomerInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfos.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Transaction.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/CustomerInfo.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfos.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/PurchasesDelegate.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/StoreTransaction.ios.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/models/Transaction.ios.kt
  datetime/api/datetime.api
  datetime/api/datetime.klib.api
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/CustomerInfo.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/EntitlementInfo.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/Transaction.kt
  either/api/either.klib.api
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/CustomerInfo.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfos.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Store.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/Transaction.android.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/VerificationResult.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/CustomerInfo.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfos.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/Transaction.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/VerificationResult.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/ktx/Map.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/ktx/NSDate.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/CustomerInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/EntitlementInfos.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/VerificationResult.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/StoreProduct.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Transaction.kt
  result/api/result.klib.api
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/androidMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptionsKtx.kt
Labels: refactor

#162 Wraps the native Android LogHandler if necessary
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/LogHandler.android.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/LogHandler.ios.kt
Labels: refactor

#163 Converts the last few data classes to regular classes.
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/PurchasesAreCompletedBy.kt
Labels: refactor

#165 Updates the API dump
  core/api/core.api
  core/api/core.klib.api
  either/api/either.api
  either/api/either.klib.api
  models/api/models.api
  models/api/models.klib.api
Labels: ci

#166 Removes unused Locale
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/i18n/Locale.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/i18n/Locale.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/i18n/Locale.ios.kt
Labels: breaking, refactor

#167 Updates the KobanKat migration guide
  migrations/KobanKat-MIGRATION.md
Labels: documentation, docs

#169 :update_hybrid_common lane also updates mappings.podspec and models.podspec
  fastlane/Fastfile
Labels: ci

#170 Fixes a PaywallListener crash
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/rememberLoggingPaywallListener.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptionsKtx.kt
Labels: bug, fix
