Repository RevenueCat/purchases-kmp, pull requests merged in 2025-01, with the labels that each got.

#301 Sets the deployment target of the UI module to 15.
  core/build.gradle.kts
  gradle/libs.versions.toml
  mappings/build.gradle.kts
  models/build.gradle.kts
  revenuecatui/build.gradle.kts
  revenuecatui/revenuecatui.podspec
Labels: pr:other

#302 Adds `enableAdServicesAttributionTokenCollection()`
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
Labels: pr:feat

#291 Support Redeeming iOS Win-Back Offers on Developer Paywalls
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/DiscountTypeAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/WinBackOfferAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/Screen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/WinBackTestingScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/OfferingsSection.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  either/api/either.api
  either/api/either.klib.api
  either/src/commonMain/kotlin/com/revenuecat/purchases/kmp/either/Either.kt
  iosApp/Podfile.lock
  iosApp/iosApp.xcodeproj/project.pbxproj
  iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
  iosApp/iosApp/SKConfig.storekit
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/DiscountType.ios.kt
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/WinBackOffer.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/DiscountType.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/WinBackOffer.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/errors.kt
  result/api/result.api
  result/api/result.klib.api
  result/src/commonMain/kotlin/com/revenuecat/purchases/kmp/result/Result.kt
Labels: pr:feat, feat:Win-Back Offers
