Repository RevenueCat/purchases-kmp, pull requests merged in 2025-09, with the labels that each got.

#481 Add warning with 2.x issues to all versions since 2.0.0 in CHANGELOG
  CHANGELOG.md
Labels: pr:other

#505 Fixes a potential crash on Android when calling `purchase()` in rapid succession
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/di/AndroidProvider.kt
Labels: pr:fix

#506 Adds purchase buttons for packages and products to the tester app.
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/PackageRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/StoreProductRow.kt
Labels: pr:other

#517 Update Gradle wrapper-validation to 4 for the `dependency-submission` GitHub Action
  .github/workflows/main.yml
Labels: pr:other

#514 Moves Instant properties to `:purchases-kmp-core`
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/CustomerInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/EntitlementInfoAPI.kt
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/TransactionAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/CustomerInfoSection.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/EntitlementInfoRow.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/TransactionRow.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/CustomerInfo.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/EntitlementInfo.kt
  datetime/src/commonMain/kotlin/com/revenuecat/purchases/kmp/datetime/Transaction.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/CustomerInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/EntitlementInfo.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/Transaction.kt
Labels: pr:other, pr:force_minor
