Repository RevenueCat/purchases-kmp, pull requests merged in 2025-03, with the labels that each got.

#341 Only runs tests once on release branches, instead of twice.
  .circleci/config.yml
Labels: pr:other

#340 Avoids unnecessary scrolling delay on iOS paywalls
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
Labels: pr:fix

#343 feat: Introduce CustomerCenter
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/Screen.kt
  iosApp/Podfile.lock
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/androidMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/CustomerCenter.kt
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/CustomerCenter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/CustomerCenter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitCustomerCenter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIViewKtx.kt
Labels: pr:feat

#352 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#353 Attempts to fix ffi by removing the platform specification.
  Gemfile
  Gemfile.lock
Labels: pr:other
