Repository RevenueCat/purchases-kmp, pull requests merged in 2025-02, with the labels that each got.

#316 Adds `checkTrialOrIntroPriceEligibility()`
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesCommonAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/components/StoreProductRow.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Coroutines.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ktx/Map.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  iosApp/Podfile.lock
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/IntroEligibilityStatus.ios.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/IntroEligibilityStatus.kt
Labels: pr:feat

#313 [Paywalls V2] Deprecate PaywallFooter in favor of OriginalTemplatePaywallFooter
  apiTester/src/commonMain/kotlin/com/revenuecat/purchases/kmp/apitester/PaywallAPI.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  revenuecatui/api/revenuecatui.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/androidMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/OriginalTemplatePaywallFooter.kt
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallFooter.kt
  revenuecatui/src/commonMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptions.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallFooter.kt
Labels: pr:RevenueCatUI, pr:other

#326 Fix crash when mapping store type RCBilling to KMP
  mappings/src/iosMain/kotlin/com/revenuecat/purchases/kmp/mappings/EntitlementInfo.ios.kt
Labels: pr:fix

#289 Support web redemption links
  apiTester/src/androidMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  apiTester/src/iosMain/kotlin/com/revenuecat/purchases/kmp/apitester/PurchasesErrorCodeAPI.kt
  composeApp/src/androidMain/AndroidManifest.xml
  composeApp/src/androidMain/kotlin/com/revenuecat/purchases/kmp/sample/MainActivity.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/DeepLinkHandler.kt
  core/api/core.api
  core/api/core.klib.api
  core/src/androidMain/kotlin/com/revenuecat/purchases/kmp/Purchases.android.kt
  core/src/commonMain/kotlin/com/revenuecat/purchases/kmp/Purchases.kt
  core/src/iosMain/kotlin/com/revenuecat/purchases/kmp/Purchases.ios.kt
  iosApp/iosApp/Info.plist
  iosApp/iosApp/iOSApp.swift
  mappings/src/androidMain/kotlin/com/revenuecat/purchases/kmp/mappings/RedeemWebPurchaseListener.android.kt
  models/api/models.api
  models/api/models.klib.api
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/RedeemWebPurchaseListener.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/WebPurchaseRedemption.kt
  models/src/commonMain/kotlin/com/revenuecat/purchases/kmp/models/errors.kt
Labels: pr:feat
