Repository RevenueCat/purchases-kmp, pull requests merged in 2025-07, with the labels that each got.

#428 Update workflows/issue-notifications.yml@v2
  .github/workflows/issue-notifications.yml
Labels: pr:other

#430 Migrates publishing to Central Portal.
  build.gradle.kts
  fastlane/Fastfile
Labels: pr:other

#435 Simpler approach to UIKit animations using constraints
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ConstrainingViewController.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitCustomerCenter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/ViewControllerWrapper.kt
Labels: pr:other

#427 Fixes Paywall and Customer Center transition animations on iOS
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/App.kt
  composeApp/src/commonMain/kotlin/com/revenuecat/purchases/kmp/sample/MainScreen.kt
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitCustomerCenter.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIKitPaywall.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/UIViewKtx.kt
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/modifier/layoutViewController.kt
Labels: pr:fix

#444 Adjusts Renovate setup in line with our other repos.
  .github/renovate.json
  .github/workflows/renovate.yml
  renovate.json
Labels: pr:other

#446 Add Codelab instruction on the README file
  README.md
Labels: documentation, pr:other

#392 Bump Kotlin to 2.1.10 and JetBrains Compose to 1.8.0 stable
  README.md
  apiTester/build.gradle.kts
  build.gradle.kts
  composeApp/build.gradle.kts
  core/api/core.klib.api
  core/core.podspec
  either/api/either.klib.api
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  mappings/mappings.podspec
  models/api/models.klib.api
  models/models.podspec
  result/api/result.klib.api
  revenuecatui/api/revenuecatui.klib.api
  revenuecatui/build.gradle.kts
  revenuecatui/revenuecatui.podspec
  revenuecatui/src/iosMain/kotlin/com/revenuecat/purchases/kmp/ui/revenuecatui/PaywallOptionsKtx.kt
Labels: pr:dependencies
